Added array to avoid repeating drawn numbers
meetupjavasaopaulo/java-meetup-lottery pull request #5
Opened 2019-10-03 04:14 UTC by Andy9822

Implemented logic to store winning numbers in an array and avoid drawing a guest that has already been drawn.

2019-10-06 04:19 UTC, boaglio requested changes

2019-10-06 04:19 UTC, boaglio commented on src/main/java/com/meetupjavasaopaulo/lottery/HomeController.java
> +
essa linha não compila

2019-10-06 04:19 UTC, boaglio commented on src/main/java/com/meetupjavasaopaulo/lottery/HomeController.java
> +			}while(winningNumbers.contains(lottery));
esse loop introduziu um novo bug: se a quantidade de sorteios se igualar ao de sorteados, o loop fica infinito

2019-10-07 00:27 UTC, Andy9822 commented on src/main/java/com/meetupjavasaopaulo/lottery/HomeController.java
> +			}while(winningNumbers.contains(lottery));
Concordo, não havia pensado nessa possibilidade.
Embora acredito que faria mais sentido apenas sortear a loteria quando houvesse disponibilidade de números para isso.

Então que houvesse um método que verifica que "possa ser efetuado um sorteio" e, caso positivo, chamar o método /bloco atual de sorteio

2023-10-11 14:37 UTC, closed without merging